spring:
  application:
    name: eureka-server
  # Spring Boot Admin (Optional but recommended format)
  # NOTE: The context-path property is commonly set on the server level now.
  # If you are using Spring Boot Admin, ensure your dependencies are correct.
  boot:
    admin:
      client:
        url: http://localhost:8070/admin # Assuming admin runs on the same server for simplicity
      context-path: /admin # Retained the original property for compatibility

server:
  port: 8070

eureka:
  instance:
    hostname: eurekaserver
  client:
    # As a server, it does not register itself or fetch the registry
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      
  server:
    # Recommended minimum value is 1000ms. 5ms is extremely low and can cause issues.
    # Updated to 1000ms (1 second) to prevent potential stability issues.
    waitTimeInMsWhenSyncEmpty: 1000 
    
management:
  endpoints:
    web:
      exposure:
        include: "*"