server:
  port: 8072

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka/
      
spring:
  # TRACING: MIGRATED to Micrometer Tracing for Spring Boot 3
  # REMOVED: zipkin:
  # REMOVED:   baseUrl: http://zipkin:9411
  # REMOVED: sleuth:
  # REMOVED:   sampler:
  # REMOVED:     percentage: 1
  
  cloud:
    # LOAD BALANCER: Ribbon is replaced by Spring Cloud LoadBalancer, and this property is no longer used.
    # REMOVED: loadbalancer.ribbon.enabled: false
    
    gateway:
      routes:
      - id: organization-service
        uri: lb://organization-service
        predicates:
        - Path=/organization/**
        filters:
        - RewritePath=/organization/(?<path>.*), /$\{path}
        - RemoveRequestHeader=Cookie,Set-Cookie
      - id: licensing-service
        uri: lb://licensing-service
        predicates:
        - Path=/license/**
        filters:
        - RewritePath=/license/(?<path>.*), /$\{path}
        - RemoveRequestHeader=Cookie,Set-Cookie
          
management:
  endpoints:
    web:
      exposure:
        include: "*"
  # TRACING: New Micrometer Tracing configuration
  tracing:
    sampling:
      probability: 1.0 # Sets 100% sampling rate (replaces sleuth.sampler.percentage: 1)
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans # New property for Zipkin endpoint (replaces spring.zipkin.baseUrl)